NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/ca.store1.omarket.com-cert.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/ca.store1.omarket.com-cert.pem
    OrganizationalUnitIdentifier: peer
